package com.supermart.iot.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Audit record written to {@code device_threshold_audit} whenever a device
 * is decommissioned via the soft-delete endpoint (DELETE /devices/{id}).
 *
 * <p>Retains the decommissioning actor (email), the device ID, and the
 * timestamp to satisfy compliance and traceability requirements (AC-6).</p>
 */
@Entity
@Table(name = "device_threshold_audit")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class DeviceDecommissionAudit {

    /**
     * Surrogate primary key — auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "audit_id")
    private Long auditId;

    /**
     * The IoT device that was decommissioned.
     */
    @Column(name = "device_id", nullable = false)
    private Long deviceId;

    /**
     * The event type recorded.  Always {@code "DECOMMISSIONED"} for rows
     * created by this audit path.
     */
    @Column(name = "event_type", nullable = false, length = 30)
    private String eventType;

    /**
     * Email of the ADMIN user who triggered the decommission operation.
     */
    @Column(name = "performed_by", nullable = false)
    private String performedBy;

    /**
     * Wall-clock timestamp at which the decommission was recorded.
     */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
}
